name: linter-and-test-check
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: npm packages install
        run: npm i
      - name: fix all
        run: make lint-fix
      - name: check linter status
        run: make lint
  tests-check:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: npm packages install
          run: npm i
        - name: gendiff tests status
          run: make test